### ISSUE TITLE
Consider joining forces with python-ctd

### ISSUE THREAD

**Issue by j08lue** [castelao/seabird#18]
It might be a good idea to join forces with [python-ctd](https://github.com/pyoceans/python-ctd).

Advantages of `python-ctd`:
* Data is returned as versatile Pandas dataframes
* Parses CTD data from different instruments

Valuable contributions from `PySeabird`:
* Experience with different CNV flavors
* NetCDF export

Just an idea... =)

**Comment by castelao** [comment]
Hello,

thanks for the message. Despite both packages handle seabird's CTD files, I believe that they have different goals. There is an overlap, but both packages explore different niches of use. PySeabird is also a support package for [CoTeDe](http://cotede.castelao.net), that you might find useful.

You have some interesting packages.

Cheers,

**Comment by j08lue** [comment]
@castelao Alright, no worries. Thanks for the link!
