### ISSUE TITLE
Problem for importing seabird. "ImportError: No module named 'exceptions'"

### ISSUE THREAD

**Issue by DavidHOTIN** [castelao/seabird#23]
Hello,

I'm a new user on phython. For my work, I downloaded the package seabird. When I tried do import it on the shell I had the error message:
ImportError: No module named 'exceptions'

I work on the IEP Pyzo 2015a version. My python version is a 3+ (3.4.1 exactly).
I work under Windows seven.

It was on the seabird 0.6.1 version.

NB: Now I have upgrade to the seabird 0.6.2 and the problem is fixed.

**Comment by castelao** [comment]
Thanks for the note David.

If you have trouble again with this package or find another bug, please, open a new issue here and I'll work on that.
