### ISSUE TITLE
Warnings during development setup

### ISSUE THREAD

**Issue by OlyDLG** [castelao/seabird#27]
OS/Env: Mac OS 10.10.5, Terminal 2.5.3 (343.7), Anaconda 3.14.1, Python 3.5.1 compiled w/ GCC 4.2.1, following conda installation instructions commit c28e2f6. (Anything else one may need to know?)

The "python setup.py develop" step produced the following (non-fatal) warnings:

warning: no previously-included files matching '__pycache__' found under directory '*'
warning: no previously-included files matching '*.py[co]' found under directory '*'
warning: no files found matching 'make.bat' under directory 'docs'

Subsequent running of tests produced no problems, however.

**Comment by castelao** [comment]
Thank you very much @OlyDLG !

make.bat included, and you can ignore the warnings for missing pycache and .py[co].
