### ISSUE TITLE
Errors running flake8 seabird tests

### ISSUE THREAD

**Issue by OlyDLG** [castelao/seabird#29]
OS/Env: Mac OS 10.10.5, Terminal 2.5.3 (343.7), Anaconda 3.14.1, Python 3.5.1 compiled w/ GCC 4.2.1, following conda installation instructions commit c28e2f6. (Anything else one may need to know?)

Checked-out to a new branch to work on Issue #28; made my changes, then, even though I hadn't "touched" any Python source (except earlier I ran "less" on all of them, just to have a look), I tried "flake8 seabird tests" just to check; I got:

(seabird)Davids-MacBook-Air:seabird DLG$ flake8 seabird tests
seabird/__init__.py:7:1: E265 block comment should start with '# '
seabird/__init__.py:9:1: E265 block comment should start with '# '
seabird/checks.py:6:1: W391 blank line at end of file
seabird/cnv.py:17:1: E265 block comment should start with '# '
seabird/cnv.py:23:1: E265 block comment should start with '# '
seabird/cnv.py:104:21: E128 continuation line under-indented for visual indent
seabird/cnv.py:107:13: E265 block comment should start with '# '
seabird/cnv.py:108:13: E265 block comment should start with '# '
seabird/cnv.py:137:80: E501 line too long (94 > 79 characters)
seabird/cnv.py:138:80: E501 line too long (85 > 79 characters)
seabird/cnv.py:152:80: E501 line too long (83 > 79 characters)
seabird/cnv.py:158:80: E501 line too long (83 > 79 characters)
seabird/cnv.py:162:25: E124 closing bracket does not match visual indentation
seabird/cnv.py:197:80: E501 line too long (86 > 79 characters)
seabird/cnv.py:214:17: E128 continuation line under-indented for visual indent
seabird/cnv.py:220:21: E251 unexpected spaces around keyword / parameter equals
seabird/cnv.py:220:23: E251 unexpected spaces around keyword / parameter equals
seabird/cnv.py:227:13: E265 block comment should start with '# '
seabird/cnv.py:253:17: E265 block comment should start with '# '
seabird/cnv.py:256:17: E265 block comment should start with '# '
seabird/cnv.py:258:25: E128 continuation line under-indented for visual indent
seabird/cnv.py:262:80: E501 line too long (112 > 79 characters)
seabird/cnv.py:263:21: E265 block comment should start with '# '
seabird/cnv.py:263:80: E501 line too long (106 > 79 characters)
seabird/cnv.py:266:21: E265 block comment should start with '# '
seabird/cnv.py:266:80: E501 line too long (83 > 79 characters)
seabird/cnv.py:267:80: E501 line too long (84 > 79 characters)
seabird/cnv.py:269:17: E265 block comment should start with '# '
seabird/cnv.py:271:17: E265 block comment should start with '# '
seabird/cnv.py:272:17: E265 block comment should start with '# '
seabird/cnv.py:275:25: E128 continuation line under-indented for visual indent
seabird/cnv.py:280:25: E128 continuation line under-indented for visual indent
seabird/cnv.py:283:25: E128 continuation line under-indented for visual indent
seabird/cnv.py:299:9: E265 block comment should start with '# '
seabird/cnv.py:327:21: E128 continuation line under-indented for visual indent
seabird/cnv.py:328:21: E128 continuation line under-indented for visual indent
seabird/cnv.py:330:25: E128 continuation line under-indented for visual indent
seabird/cnv.py:331:25: E128 continuation line under-indented for visual indent
seabird/cnv.py:334:25: E128 continuation line under-indented for visual indent
seabird/cnv.py:335:25: E128 continuation line under-indented for visual indent
seabird/cnv.py:337:25: E128 continuation line under-indented for visual indent
seabird/cnv.py:338:25: E128 continuation line under-indented for visual indent
seabird/cnv.py:342:17: E265 block comment should start with '# '
seabird/cnv.py:343:17: E265 block comment should start with '# '
seabird/cnv.py:346:80: E501 line too long (80 > 79 characters)
seabird/cnv.py:352:25: E128 continuation line under-indented for visual indent
seabird/cnv.py:353:25: E128 continuation line under-indented for visual indent
seabird/cnv.py:355:25: E128 continuation line under-indented for visual indent
seabird/cnv.py:356:25: E128 continuation line under-indented for visual indent
seabird/cnv.py:359:25: E128 continuation line under-indented for visual indent
seabird/cnv.py:360:25: E128 continuation line under-indented for visual indent
seabird/cnv.py:362:25: E128 continuation line under-indented for visual indent
seabird/cnv.py:363:25: E128 continuation line under-indented for visual indent
seabird/cnv.py:368:17: E265 block comment should start with '# '
seabird/cnv.py:369:17: E265 block comment should start with '# '
seabird/cnv.py:372:80: E501 line too long (82 > 79 characters)
seabird/cnv.py:417:80: E501 line too long (95 > 79 characters)
seabird/cnv.py:442:9: E265 block comment should start with '# '
seabird/cnv.py:486:80: E501 line too long (100 > 79 characters)
seabird/netcdf.py:14:1: E302 expected 2 blank lines, found 1
seabird/netcdf.py:22:42: E901 SyntaxError: invalid syntax
seabird/netcdf.py:30:5: E265 block comment should start with '# '
seabird/netcdf.py:31:31: E702 multiple statements on one line (semicolon)
seabird/netcdf.py:48:21: E128 continuation line under-indented for visual indent
seabird/netcdf.py:49:80: E501 line too long (126 > 79 characters)
seabird/netcdf.py:53:13: E265 block comment should start with '# '
seabird/utils.py:31:80: E501 line too long (93 > 79 characters)
tests/test_import.py:4:1: E302 expected 2 blank lines, found 1
tests/test_import.py:5:5: F401 'numpy' imported but unused
tests/test_import.py:6:5: F401 'yaml' imported but unused
tests/test_import.py:8:5: F401 'seabird' imported but unused
tests/test_import.py:9:5: F401 'CNV' imported but unused
tests/test_import.py:10:5: F401 'fCNV' imported but unused
tests/test_parse.py:13:1: E302 expected 2 blank lines, found 1
tests/test_parse.py:19:13: F841 local variable 'profile' is assigned to but never used
tests/test_rules.py:13:1: E302 expected 2 blank lines, found 1
tests/test_rules.py:24:17: E128 continuation line under-indented for visual indent
tests/test_rules.py:29:1: E302 expected 2 blank lines, found 1
tests/test_rules.py:30:25: E711 comparison to None should be 'if cond is None:'
tests/test_serialize.py:12:1: F401 'np' imported but unused

(but all py.test tests passed).

Reverted changes to overview.rst, tried flake8 again, same result.

**Comment by OlyDLG** [comment]
So, I guess all of these appear to be merely stylistic issues, which I'm OK ignoring if you, GUI, say it's OK (and as long as the py.test tests still pass and the git code comparison doesn't flag them as differing from the Master branch, both of which, presently are true).

**Comment by castelao** [comment]
Sorry for the delay @OlyDLG .You're right, the most important is the py.test. Yes you can you can move on, I'll work on those issues pointed by flake8.

Thanks!

**Comment by OlyDLG** [comment]
OK, thanks!

**Comment by castelao** [comment]
I'm leaving the test_import off since I plan to do something different with that test.

Thanks @OlyDLG !
