### ISSUE TITLE
seabird >= 0.10.0 fCNV dies on lines with only "*"

### ISSUE THREAD

**Issue by dnowacki-usgs** [castelao/seabird#40]
Ref. #37.

This was fixed in 0.8.1, but seems to have cropped back up in 0.10.0 and 0.10.1. Any lines in .cnv files that have only an asterisk (*) on lines, e.g.:
```
* <HardwareData DeviceType='SBE19plus' SerialNumber='01906651'>
*
*    <Manufacturer>Sea-Bird Electronics, Inc.</Manufacturer>
*
*    <FirmwareVersion>2.2c</FirmwareVersion>
*
```
results in a `KeyError: 'instrument_type'`. As in #37, manually deleting the *-only lines enables the files to be read successfully by 0.10.0 and 0.10.1.

**Comment by castelao** [comment]
Thank you very much! @dnowacki-usgs, my apologies for letting that bug to come back. The new patch fixes that.

I started some refactoring, but I didn't have the chance to finish it yet. Hopefully soon.

**Comment by dnowacki-usgs** [comment]
Thanks for the quick response! 0.10.2 fixes the issue for me.
