### ISSUE TITLE
cnv2nc error: "Missing parentheses in call to 'print'"

### ISSUE THREAD

**Issue by sckw** [castelao/seabird#42]
![capture](https://user-images.githubusercontent.com/31698590/32572961-5a848ab2-c49a-11e7-8f4a-33a89929cba3.PNG)

I am trying to convert my .cnv file to a .nc file using this command. But it is returning this error. Is it something obvious that I am doing wrong here?

Thanks.

**Comment by sckw** [comment]
I assume it's because I am using Python 3, and seabird should be used on Python 2?

**Comment by castelao** [comment]
Hi @sckw. This package should be Python 3 compatible as well. Somehow I missed that print. I'll fix it and upload a new release soon.

Thank you very much for reporting this.
