### ISSUE TITLE
Demonstration notebooks

### ISSUE THREAD

**Issue by poplarShift** [castelao/seabird#46]
Just came across this library, very useful, thank you!

About the notebooks, I noticed a few things:
1) BasicsReadingData.ipynb and ProcessingData.ipynb are virtually identical.
2) They are slightly outdated (location of test data, and Python 2/3 compatibility).

Mind if I fix this?

**Comment by castelao** [comment]
Thanks @poplarShift ! Yes please, I would appreciate if you would have the time to send a PR. Thank you!
