### ISSUE TITLE
There are no rules able to parse the input

### ISSUE THREAD

**Issue by atorr018** [castelao/seabird#51]
Hi there,

I am CS student, and I found an issue with the library you are developing. I try it with other .cnv files and is working fine, but this one from 2016 is having an issue. It trows the following exception

CNVError: 'There are no rules able to parse the input. File:

you think it would be fine to send you the file so you can check the issue? or is it something I am doing wrong?

**Comment by castelao** [comment]
Hi, yes please send me a sample of your failing files.

**Comment by atorr018** [comment]
thanks, here you go:

[K83_01_000.zip](https://github.com/castelao/seabird/files/2933937/K83_01_000.zip)

**Comment by PabloOtero** [comment]
Hi Castelão, any update about this issue? I'm experiencing the same problem.

**Comment by PabloOtero** [comment]
Hi again,

I'm not sure why my code in utils.py was indented in lines 98 to 101. By usign your updated code in your repository everything works.

My old code:
`        if re.search(r, raw_text, re.VERBOSE):
            #logging.debug("Using rules from: %s" % rule_file)
            #self.rule = rule
            parsed = content_re.search(raw_text).groupdict()
            return rule, parsed
        else:
            # If haven't returned a rule by this point, raise an exception.
            #logging.error("No rules able to parse it")
            raise CNVError(tag='noparsingrule')`

And the correct one:
`        if re.search(r, raw_text, re.VERBOSE):
            #logging.debug("Using rules from: %s" % rule_file)
            #self.rule = rule
            parsed = content_re.search(raw_text).groupdict()
            return rule, parsed
        
    # If haven't returned a rule by this point, raise an exception.
    #logging.error("No rules able to parse it")
    raise CNVError(tag='noparsingrule')`

**Comment by castelao** [comment]
I'm sorry for the slow response. So is the latest commit here working for you?

**Comment by aer205** [comment]
Hello,
I'm having the same issue - do you have any advice?

**Comment by castelao** [comment]
Thanks @atorr018 !

@PabloOtero , [these lines](https://github.com/castelao/seabird/blob/92fa2c829027173b8e418ab1e58637fe439be30b/seabird/utils.py#L95-L97) should be out of the loop so that if no rule can satisfy, the function returns an error.

@PabloOtero and @aer205 , if the latest version doesn't work for you, I would need to see an example file to understand why the current rules can't parse your data. In that case, please open a new issue with the cnv text that fails. Thanks,
