### ISSUE TITLE
fCNV skips first line of data

### ISSUE THREAD

**Issue by mbiddle-bcodmo** [castelao/seabird#53]
I'm trying to read a bunch of cnv files and when I use `profile = seabird.cnv.fCNV`, I get a bunch of warnings similar to:
```
scan was supposed to has 404 values, but found only 403.
```

Looking at the cnv file at the end of the header and beginning of the data:
```
# file_type = ascii
*END*
        645      1.000      0.994    23.9880 5.4670e+04     2.8009     0.7079    55.2620     -0.102    37.0165    25.1725    23.9878    25.1725      0.994    6.79373    4.50062    196.062 -9.990e-29 -9.990e-29 0.0000e+00
        657      2.000      1.989    23.9875 5.4671e+04     2.7906     0.7145    55.2620      0.759    37.0171    25.1731    23.9871    25.1732      1.989    6.79377    4.48101    195.208 2.7714e-06       0.95 0.0000e+00
```

When looking at profile.raw_data():
```
{'data': '        657      2.000      1.989    23.9875 5.4671e+04     2.7906     0.7145    55.2620      0.759    37.0171    25.1731    23.9871    25.1732      1.989    6.79377    4.48101    195.208 2.7714e-06       0.95 0.0000e+00\n        685      3.000      2.984    23.9875 5.4671e+04     2.7847     0.6732    55.2620      0.295    37.0169    25.1729    23.9869    25.1731      2.983    6.79377    4.47007    194.731 -8.342e-07      -0.52 0.0000e+00\n 
```
and so on.

Something is telling the package to start at the second data line, not the first. Thus the line count is one less than **nvalues**. 

I have 1k+ CNV files and this happens to every one of them. 

If I stick a newline after `*END*` and before the data, it seems to work okay. I'm fine with doing that for now. But, I'm curious to figure out why it doesn't work off the shelf.

The files are similar to the sample file https://github.com/castelao/seabird/blob/master/sampledata/CTD/dPIRX003.cnv

**Comment by castelao** [comment]
@mbiddle-bcodmo, thanks!
