### ISSUE TITLE
Invalid format string for strftime() in cnv2nc

### ISSUE THREAD

**Issue by aer205** [castelao/seabird#57]
Hi,

When using cnv2nc I get the following error (and line reference):

File [filename], line 33, in cnv2nc
    nc.DATE_CREATION = datetime.now().strftime("%Y%m%s%H%M%S")
ValueError: Invalid format string

It seems to be the case for a variety of .cnv files. I'm using a Windows machine.

**Comment by botheredbybees** [comment]
I had this problem and had to edit the code so it puts the day in (a 'd' rather than a lower case 's'): 

nc.DATE_CREATION = datetime.now().strftime("%Y%m%d%H%M%S")

will have a go at putting in a pull request if I can get it working (I'm currently at sea, and bandwidth is a bit limited)

**Comment by castelao** [comment]
Thank you both! PR #58 merged, and new release submitted to pypi.
